server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/regis?useSSL=true&serverTimezone=UTC
    username: root
    password: 1037807650Hjy
